TareaG11prim/TareaG11prim/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

TareaG11prim/app/urls.py
from django.urls import path
from .views import * 

urlpatterns = [
	path('', inicio, name ='inicio'),
	path('contacto', contacto, name ='contacto'),
	path('login', login, name ='login'),
	path('agregarproducto', agregarproducto, name ='agregarproducto'),
	path('carrito', carrito, name ='carrito'),
	path('pedidos', pedidos,  name ='pedidos'),
	path('exito', exito,  name ='exito'),
	path('agregarpublicacion', agregarpublicacion,  name ='agregarpublicacion'),
	path('novedades', novedades,  name ='novedades'),
	path('mensajes', mensajes,  name ='mensajes'),
	path('borrarmensaje', borrarmensaje,  name ='borrarmensaje'),
	path('borrarencarrito', borrarencarrito,  name ='borrarencarrito'),
	path('agregarcarrito', agregarcarrito,  name ='agregarcarrito'),
	path('finalizarpedido', finalizarpedido,  name ='finalizarpedido'),
]

TareaG11prim/app/models.py
from django.db import models

# Create your models here.

class Productos(models.Model):
	_COLOR_TYPES = (
        (1, "Rojo"),
        (2, "Azul"),
        (3, "Amarillo"),
        (4, "Verde"),
        (5, "Blanco"),
        (6, "Negro"),
        (7, "Otro"),
    )

	_TIPO_TYPES = (
        (1, "Crop Top"),
        (2, "Gorro"),
        (3, "Bufanda"),
        (4, "Otro"),
    )

	nombre = models.CharField(max_length=45, blank=False)
	valor = models.IntegerField()
	color = models.IntegerField(choices=_COLOR_TYPES )
	tipo = models.IntegerField(choices=_TIPO_TYPES)
	stock = models.IntegerField()
	foto = models.ImageField(upload_to='static/images/', blank=True)


class Novedades(models.Model):
	titulo = models.CharField(max_length=45, blank=False)
	cuerpo = models.CharField(max_length=100, blank=False)
	fecha = models.DateField(auto_now=True)


class Mensajes(models.Model):
	nombre = models.CharField(max_length=45, blank=False)
	correo = models.CharField(max_length=45, blank=False)
	mensaje = models.CharField(max_length=300, blank=False)
	foto = models.ImageField(upload_to='static/images/', blank=True)
	fecha = models.DateField(auto_now=True)

class Carro(models.Model):
	productos = models.ManyToManyField(Productos, blank=True)
	activo = models.BooleanField(default = True)

class Pedidos(models.Model):
	carrito = models.ForeignKey(
        'Carro', related_name='pedidos', on_delete=models.CASCADE)
	nombre = models.CharField(max_length=45, blank=False)
	correo = models.CharField(max_length=45, blank=False)
	ciudad = models.CharField(max_length=45, blank=False)
	precio = models.IntegerField()
	finalizado = models.BooleanField(default=False)


class User(models.Model):
	nombre = models.CharField(max_length=45, blank=False)
	contraseña = models.CharField(max_length=45, blank=False)

TareaG11prim/app/views.py
from django.shortcuts import render, redirect
from .models import *
#esto es mientras 
carrito_key=0
# Create your views here.
def inicio(request):
	# if this is a POST request we need to process the form data
	if request.method == 'GET':
		if request.GET.get('nombre'):
			nombre= request.GET.get('nombre')
			return render(request, 'inicio.html', {"nombre": nombre})

	if request.method == 'POST':
		if request.POST.get('agregar'):
			return render(request, 'inicio.html', {"producto": 1})
	contexto= {}
	contexto['productos']= Productos.objects.all()		
	return render(request, 'inicio.html', contexto)

def contacto(request):
	if request.method == 'POST':
		if request.POST.get('nombre'):
			nombre = request.POST.get('nombre')
			correo = request.POST.get('correo')
			mensaje = request.POST.get('mensaje')
			if request.FILES:
				foto = request.FILES['foto']
			else:
				foto=None	
			mensaje= Mensajes(nombre=nombre, correo=correo, mensaje=mensaje, foto=foto )
			mensaje.save()
			return render(request, 'contacto.html', {'success': 1, 'nombre':nombre})
	return render(request, 'contacto.html')

def agregarproducto(request):
	if request.method == 'POST':
		nombre = request.POST.get('nombre')
		valor = request.POST.get('valor')
		color = request.POST.get('color')
		tipo = request.POST.get('tipo')
		stock = request.POST.get('stock')
		foto = request.FILES['foto']
		producto = Productos(nombre=nombre, valor=valor, color=color, tipo=tipo, stock=stock, foto=foto)
		producto.save()
		return render(request, 'agregarproducto.html', {'success':1})
	return render(request, 'agregarproducto.html')	

def login(request):
	if request.method == 'POST':
		nombre= request.POST.get('nombre')
		redir= 'inicio/' + nombre
		return redirect('/?nombre=' + nombre)
	return render(request, 'login.html')

def carrito(request):
	contexto= {}
	carro =Carro.objects.filter(pk=carrito_key).first()
	contexto['carro'] = carro
	if carro:
		contexto['productos']= contexto['carro'].productos.all()
		valor= 0
		for p in contexto['productos']:
			valor += p.valor
		contexto['valor']= valor	
	
	if request.method == 'POST':
		nombre = request.POST.get('nombre')
		correo = request.POST.get('correo')
		ciudad = request.POST.get('ciudad')
		contexto['nombre'] = nombre
		contexto['correo'] = correo
		contexto['ciudad'] = ciudad
		pedido= Pedidos(carrito=contexto['carro'], nombre=nombre, correo=correo, ciudad=ciudad, precio=valor)
		pedido.save()
		carro.activo = False

		return render(request, 'exito.html', contexto)
		
	return render(request, 'carrito.html', contexto)	

def pedidos(request):
	contexto= {}
	pedidos = Pedidos.objects.filter(finalizado = False)
	print(pedidos)
	contexto['pedidos'] = pedidos
	return render(request, 'pedidos.html',contexto)	


def exito(request):
	return render(request, 'exito.html')	

def agregarpublicacion(request):
	if request.method == 'POST':
		titulo = request.POST.get('titulo')
		cuerpo = request.POST.get('cuerpo')		
		novedad = Novedades(titulo=titulo, cuerpo=cuerpo)
		novedad.save()
		return render(request, 'agregarpublicacion.html', {'success':1})
	return render(request, 'agregarpublicacion.html')	

def novedades(request):
	contexto = {}
	contexto['novedades'] = Novedades.objects.all()

	return render(request, 'novedades.html', contexto)	

def mensajes(request):
	contexto= {}
	contexto['mensajes']= Mensajes.objects.all()

	return render(request, 'mensajes.html', contexto)		

def borrarmensaje(request):	
	if request.method == 'POST':
		mensaje = request.POST.get('mensaje')
		m = Mensajes.objects.filter(pk=mensaje)
		m.delete()
	return redirect('/mensajes')

def borrarencarrito(request):
	if request.method == 'POST':
		producto = request.POST.get('producto')
		carro = request.POST.get('carro')
		#revisar esto
		c = Carro.objects.filter(pk=carro).first()
		p = Productos.objects.filter(pk=producto).first()
		c.productos.remove(p)	
	return redirect('/carrito')

def agregarcarrito(request):
	if request.method == 'POST':
		producto = request.POST.get('producto')
		p= Productos.objects.filter(pk=producto).first()
		c = Carro.objects.filter(pk=carrito_key).first()
		if not c:
			c= Carro(pk=carrito_key)
			c.save()	
		c.productos.add(p)
		c.save()
	return redirect('/')

def finalizarpedido(request):
	if request.method == 'POST':
		pedido = request.POST.get('pedido')
		p = Pedidos.objects.filter(pk=pedido).first()
		p.finalizado = True
		p.save()
	return redirect('/pedidos')

TareaG11prim/app/templates/agregarproducto.html
{% extends 'navbar.html' %}
{% block title %}
  Agregar Producto
{% endblock title %}
{% block content %}
  <!DOCTYPE html>
  <html>
    <head>
    </head>
    <body>
      <h2>Nuevo producto</h2>
      <div class="col-sm-10">
        {% if success %}
          <div class="alert alert-success alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Producto agregado con éxito</strong> ¡Revísalo en la pestaña de inicio!.
          </div>
        {% endif %}
        <form action="agregarproducto" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <h5> Agregar nuevo producto al catálogo</h5>
          <div class="row">
            <br>
            <div class="col-sm-6 form-group">
              <p>Nombre producto: </p><input class="form-control" id="nombre" name="nombre" placeholder="Nombre Producto" type="text" required>
              <p>Valor: </p><input class="form-control" id="nombre" name="valor" placeholder="$ valor en CLP" type="number" required>
              <p>Color: </p><div class="form-group">
              <select name="color">
                <option value=1>Rojo</option>
                <option value=2>Azul</option>
                <option value=3>Amarillo</option>
                <option value=4>Verde</option>
                <option value=5>Blanco</option>
                <option value=6>Negro</option>
                <option value=7>Otro</option>
              </select>
            </div>
              <p>Tipo: </p><div class="form-group">
              <select name="tipo">
                <option value=1>Crop Top</option>
                <option value=2>Gorro</option>
                <option value=3>Bufanda</option>
                <option value=4>Otro</option>
              </select>
            </div>
            
            <p>Stock: </p><input class="form-control" id="nombre" name="stock" placeholder="Stock" type="number" required>
            <div class="form-group">
              <label for="exampleFile">Foto</label>
              <input type="file" name="foto" class="form-control-file" id="exampleFile" required>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6 form-group">
            <button class="btn btn-primary" type="submit">Enviar</button>
          </div>
        </div>
      </div>
    </form>
  </body>
</html>
{% endblock content %}

TareaG11prim/app/templates/agregarpublicacion.html
{% extends 'navbar.html' %}
{% block title %}
Nueva publicación
{% endblock title %}
{% block content %}
<!DOCTYPE html>
<html>

<head>
</head>

<body>
  <h2>Nueva publicación</h2>
  <div class="col-sm-10">
    {% if success %}
    <div class="alert alert-success alert-dismissible">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <strong>Publicación agregada con éxito</strong> ¡Revísalo en la pestaña de novedades!.
    </div>
    {% endif %}
    <form action="agregarpublicacion" method="POST">
      {% csrf_token %}
      <h5> Agregar nueva publicación</h5>
      <div class="row">
        <br>
        <div class="col-sm-6 form-group">
          <p>Título: </p><input class="form-control" id="nombre" name="titulo" placeholder="Título" type="text" required>
          <p>
            
            <p>Cuerpo: </p>
            <textarea class="form-control" id="comments" name="cuerpo" placeholder="Cuerpo de la noticia" rows="5"></textarea>
          </p>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-6 form-group">
          <button class="btn btn-primary" type="submit">Enviar</button>
        </div>
      </div>
    </form>
  </div>
</body>

</html>
{% endblock content %}

TareaG11prim/app/templates/carrito.html
{% extends 'navbar.html' %}
{% block title %}
Carro de compras
{% endblock title %}
{% block content %}
<!DOCTYPE html>
<html>

<head>
</head>

<body>
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <h3>Datos del comprador</h3>
        <form action="carrito" method="POST">
          {% csrf_token %}
          <label for="fname"><i class="fa fa-user"></i> Nombre</label>
          <input type="text" id="fname" name="nombre" placeholder="Nombre" required>
          <label for="email"><i class="fa fa-envelope"></i> Email</label>
          <input type="text" id="email" name="correo" placeholder="e-mail" required>
          <label for="city"><i class="fa fa-institution" required></i> Ciudad</label>
          <input type="text" id="city" name="ciudad" placeholder="Ciudad">
          <input type="hidden" name="carro" value={{carro.pk}}>
          <input type="hidden" name="productos" value={{productos}}>
          <input type="hidden" name="valor" value={{valor}}>

          <br><br>
          <p><input type="submit" class="btn btn-primary" value="Finalizar" name="agregar"></p>
        </form>
      </div>
      <div class="col-sm-6">
        <h3>Productos</h3>
        <table class="table table-image">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">Imagen</th>
              <th scope="col">Producto</th>
              <th scope="col">Color</th>
              <th scope="col">Precio</th>
              <th scope="col"> </th>
            </tr>
          </thead>
          <tbody>
            {%for p in productos %}
            <tr>
              <th scope="row">1</th>
              <td class="w-25">
                <img src="{{p.foto.url}}" alt="Crop Top manga caida" class="img-fluid img-thumbnail" width="100" height="50">
              </td>
              <td>{{p.nombre}}</td>
              <td>{{p.get_color_display}}</td>
              <td>{{p.valor}}</td>
              <form action="borrarencarrito" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="producto" value={{p.pk}}>
                <input type="hidden" name="carro" value={{carro.pk}}>
                <td><input type="submit" value="X" name="borrar"></td>
              </form>
            </tr>
            {% endfor%}
            <tr>
              <th scope="row"></th>
              <td class="w-25">
                Total:
              </td>
              <td></td>
              <td> </td>
              <td></td>
              <td>{{valor}}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      Los envíos a regiones se realizarán con envío por pagar.
    </div>
  </div>
</body>

</html>
{% endblock content %}

TareaG11prim/app/templates/contacto.html
{% extends 'navbar.html' %}
{% block title %}
Contacto
{% endblock title %}
{% block content %}

<div class="container-fluid bg-grey">
  <h2 class="text-center">Contáctame</h2>
  <div class="row">
    <div class="col-sm-2">
      <p></p>
    </div>
    <div class="col-sm-3">
      <p>
        <h3>Valentina Garrido.</h3>
      </p>
      <p><span class="glyphicon glyphicon-map-marker"></span> Santiago, Chile</p>
      <p><span class="glyphicon glyphicon-phone"></span> +56981369778</p>
      <p><span class="glyphicon glyphicon-envelope"></span> tejidosvali@gmail.com</p>
      <p><a href="https://www.instagram.com/tejidosvali" target="_blank"><i class="fa fa-instagram"></i></a> @tejidosvali</p>
    </div>
    <div class="col-sm-5">
      {% if success %}
      <div class="alert alert-success alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>{{nombre}}, tu envío fue exitoso</strong> Serás contactado/a a la brevedad.
      </div>
      {% endif %}
      <h5> ¿Quieres algo que no está en el catálogo? Te contactaré.</h5>
      <div class="row">
        <br>
        <form action="contacto" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="col-sm-6 form-group">
            <input class="form-control" id="nombre" name="nombre" placeholder="Nombre" type="text" required>
          </div>
          <div class="col-sm-6 form-group">
            <input class="form-control" id="email" name="correo" placeholder="Email" type="email" required>
          </div>
      </div>
      <textarea class="form-control" id="comments" name="mensaje" placeholder="Mensaje" rows="5"></textarea><br>
      <div>
        <p> ¿No sabes como describirlo? ¡Adjunta una imagen de referencia!</p>
         <div class="form-group">
              <label for="exampleFile">Foto</label>
              <input type="file" name="foto" class="form-control-file" id="exampleFile">
            </div>
      </div>
      <br>
      <div class="row">
        <div class="col-sm-8 form-group">
          <button type="submit" class="btn btn-primary">Enviar</button>
        </div>
      </div>
      </form>
    </div>
    <div class="col-sm-2">
      <p></p>
    </div>
  </div>
</div>
{% endblock content %}

TareaG11prim/app/templates/exito.html
{% extends 'navbar.html' %}
{% block title %}
Pedido exitoso
{% endblock title %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <h2>Pedido realizado con éxito.</h2> <br>
      <strong>Código de pedido: XADDSF</strong>
      <br>
      <br>
      Se debe envíar tranferencia bancaria a: <br><br>
      <strong>
        <p>Cuenta Vista Banco estado</p>
        <p>
          Nombre: Valentina Garrido.</p>
        <p> rut: 1.111.111-9</p>
        <p> Número de cuenta: 1.111.111</p>
        <p>Corre0: tejidosvali@gmail.com</p>
      </strong>
      <br><br>La transferencia debe ser realizada dentro de las primeras 24 horas y adjuntar el código identificador del pedido.
      Si luego de pasadas 24 horas de la recepción del pedido no se ha recibido la transferencia, el pedido será eliminado.
    </div>
    <div class="col-sm-6">
      <table class="table table-image">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col">Imagen</th>
            <th scope="col">Producto</th>
            <th scope="col">Color</th>
            <th scope="col">Precio</th>
            <th scope="col"> </th>
          </tr>
        </thead>
        <tbody>
          {%for p in productos %}
            <tr>
              <th scope="row">1</th>
              <td class="w-25">
                <img src="{{p.foto.url}}" alt="Crop Top manga caida" class="img-fluid img-thumbnail" width="100" height="50">
              </td>
              <td>{{p.nombre}}</td>
              <td>{{p.color}}</td>
              <td>{{p.valor}}</td>
            </tr>
            {% endfor%}
            <tr>
              <th scope="row"></th>
              <td class="w-25">
                Total:
              </td>
              <td></td>
              <td> </td>
              <td></td>
              <td>{{valor}}</td>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>
{% endblock content %}

TareaG11prim/app/templates/inicio.html
{% extends 'navbar.html' %}
{% block title %}
Inicio
{% endblock title %}
{% block content %}
<div class="container-fluid text-center bg-grey">
  {% if nombre %}
  <div class="alert alert-success alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>Bienvenide {{nombre}} </strong>
  </div>
  {% endif %}
  {% if producto %}
  <div class="alert alert-success alert-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong>Producto Agregado</strong> <a href=/carrito> ver carrito </a> </div> {% endif %} <h2>Productos </h2><br>
      <h4></h4>
      <!-- Control buttons -->
      <div id="myBtnContainer">
        <button class="btn active" onclick="filterSelection('all')"> Todo</button>
        <button class="btn" onclick="filterSelection('1')"> Crop Tops</button>
        <button class="btn" onclick="filterSelection('2')"> Gorros </button>
        <button class="btn" onclick="filterSelection('3')"> Bufandas</button>
        <button class="btn" onclick="filterSelection('4')"> Otros</button>
      </div>
      <br>
      <!-- The filterable elements. Note that some have multiple class names (this can be used if they belong to multiple categories) -->
      <div class="container">
        <div class="row">
          {%for p in productos%}
          <div class="col-sm-4">
            <div class="filterDiv {{p.tipo}}">
              <p><img src="{{p.foto.url}}" alt="Gorros" width="350" height="250"></p>
              <p><strong>{{p.nombre}}</strong></p>
              <p>{{p.valor}} c/u</p>
              <p>{{p.stock}}</p>
              <form action="agregarcarrito" method="POST">
                {% csrf_token %}
                <input type="hidden" name="producto" value={{p.pk}}>
                <p><input type="submit" value="Agregar" name="agregar"></p>
              </form>
            </div>
          </div>
          
          {% endfor %}
          
         
          
        </div>
      </div>

      {% endblock content %}

TareaG11prim/app/templates/inputs.html
{% extends 'navbar.html' %}

{% block title %}
Inputs
{% endblock title %}

{% block content %}

<div id="descripcion" class="container">
    <h1>Lista de Inputs</h1>

    <form action="#" autocomplete="off">

    <div class="form-group">
      <label for="exampleInputEmail1">Type: text</label>
      <input type="text" class="form-control" id="exampleText" placeholder="Ingrese texto" name="inputText">
    </div>

    <div class="form-group">
      <label for="exampleFormControlTextarea">Type: textarea</label>
      <textarea class="form-control" id="exampleFormControlTextarea" rows="3"></textarea>
    </div>

     <div class="form-group">
      <label for="exampleNumber">Type: number</label>
      <input type="number" class="form-control" id="exampleNumber" placeholder="Ingrese numero" name="inputNumber">
    </div>

    <div class="form-group">
      <label for="exampleNumber">Type: date</label>
      <input type="date" class="form-control" id="exampleDate" placeholder="Ingrese Fecha" name="inputDate">
    </div>

    <div class="form-group">
      <label for="exampleInputEmail1">Type: email</label>
      <input type="email" class="form-control" id="exampleEmail" placeholder="Ingrese email" name="inputEmail">
    </div>

    <div class="form-group">
      <label for="exampleInputPassword1">Type: password</label>
      <input type="password" class="form-control" id="examplePassword" placeholder="ingrese contraseña" name="inputPassword">
    </div>

    Type: checkbox
    <div class="form-group">

    <div class="form-check form-check-inline" >
      <input type="checkbox" class="form-check-input" id="exampleCheck1" name="inputCheck1">
      <label class="form-check-label" for="exampleCheck1">Check1</label>
    </div>


    <div class="form-check form-check-inline" >
      <input type="checkbox" class="form-check-input" id="exampleCheck2" name="inputCheck2">
      <label class="form-check-label" for="exampleCheck2">Check2</label>
    </div>

    <div class="form-check form-check-inline" >
      <input type="checkbox" class="form-check-input" id="exampleCheck3" name="inputCheck3">
      <label class="form-check-label" for="exampleChec3">Check3</label>
    </div>
    </div>

    <div class="form-group">
      <label for="exampleFormControlSelect1">Type: select</label>
      <select class="form-control" id="exampleSelect" name="input Select">
        <option value="1">Opcion 1</option>
        <option value="2">Opcion 2</option>
        <option value="3">Opcion 3</option>
        <option value="4">Opcion 4</option>
        <option value="5">Opcion 5</option>
      </select>
    </div>

    <div class="form-group">
      <label for="exampleFile">Type: file</label>
      <input type="file" class="form-control-file" id="exampleFile">
    </div>

    Type: radio
    <div class="form-check">
      <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
      <label class="form-check-label" for="exampleRadios1">
        Radio 1
      </label>
    </div>
    <div class="form-check">
      <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2" value="option2">
      <label class="form-check-label" for="exampleRadios2">
        Radio 2
      </label>
    </div>
    <div class="form-check">
      <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios3" value="option2">
      <label class="form-check-label" for="exampleRadios3">
        Radio 3
      </label>
    </div>

    <br>


    <div class="form-group">
    <button type="submit" class="btn btn-primary">Enviar</button>
    </div>
  
  </form>
       
</div>

{% endblock content %}

TareaG11prim/app/templates/login.html
{% extends 'navbar.html' %}

{% block title %}
Login
{% endblock title %}

{% block content %}
<div id="description" class="col-sm-5" style="margin-left: 400px">
<form action="login" method="POST" >
  {% csrf_token %}
  <div class="form-group" >
    <label for="email">Usuario: </label>
    <input name='nombre' type="text" class="form-control" id="user" required>
  </div>
  <div class="form-group">
    <label for="pwd">Password: </label>
    <input type="password" class="form-control" id="pwd"required>
  </div>
  <div class="checkbox">
    <label><input type="checkbox"> Recordarme</label>
  </div>
  <button type="submit" class="btn btn-primary" style="margin-left: 100px">Iniciar sesión</button>
</form> 
</div>
{% endblock content %}

TareaG11prim/app/templates/mensajes.html
{% extends 'navbar.html' %}
{% block title %}
  Mensajes
{% endblock title %}
{% block content %}
  <div class="container">
    <h3> Mensajes recibidos</h3>
    <table class="table table-image">
      <thead>
        <tr>
          <th scope="col">Mensaje</th>
          <th scope="col">Imagen</th>
          <th scope="col">Cliente</th>
          <th scope="col"> </th>
        </tr>
      </thead>
      <tbody>
        {% for m in mensajes %}
          <tr>
            <th scope="row">{{m.mensaje}}</th>
            <td class="w-15">
              {% if m.foto %}
              <img src="{{m.foto.url}}" alt="Crop Top manga caida" class="img-fluid img-thumbnail" width="100" height="50">
              {% endif %}
            </td>
            <td>{{m.nombre}}<br>
            {{m.correo}}
            {{m.pk}}</td>
            <form action="borrarmensaje" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              <input type="hidden" name="mensaje" value={{m.pk}}>
              <td><input type="submit" value="X" name="borrar"></td>
            </form>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock content %}

TareaG11prim/app/templates/pedidos.html
{% extends 'navbar.html' %}
{% block title %}
Pedidos
{% endblock title %}
{% block content %}
<div class="container">
  <h3> Pedidos Pendientes</h3>
  <table class="table table-image">
    <thead>
      <tr>
        <th scope="col">Código de Pedido</th>
        <th scope="col">Imagen</th>
        <th scope="col">Producto</th>
        <th scope="col">Color</th>
        <th scope="col">Cliente</th>
        <th scope="col">Valor</th>
        <th scope="col"> </th>
      </tr>
    </thead>
    <tbody>
      {%for p in pedidos %}
      <tr>
        <th scope="row">{{p.pk}}</th>
        <td class="w-15">
          {% for prod in p.carrito.productos.all %}
          <img src="{{prod.foto.url}}" class="img-fluid img-thumbnail" width="100" height="50">
          <br>
          {% endfor %}
        </td>
        <td>
          {%for prod in p.carrito.productos.all%}
          {{prod.nombre}}<br>
          {% endfor %}</td>
        <td> {%for prod in p.carrito.productos.all%}
          {{prod.get_color_display}}<br>
          {% endfor %}
        </td>
        <td>{{p.nombre}} <br>
          {{p.correo}}</td>
        <td> {{p.precio}}</td>
        <td><form action="finalizarpedido" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="pedido" value={{p.pk}}>
                <td><input type="submit" value="Finalizar" name="borrar"></td>
              </form></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}